services:
  app:
    image: mysociety/la-plans-promises:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/la_plans_promises      
    volumes:
      - ./:/workspaces/la_plans_promises/