#!/bin/bash 

echo "--------------"
echo "Running pytest"
echo "--------------"
poetry run pytest
pytestexit=$?
echo "--------------"
echo "Running black"
echo "--------------"
poetry run black . --check
blackexit=$?

echo "Pytest status: $pytestexit"
echo "Black status: $blackexit"

sum="$(($pytestexit + $blackexit))"

if [ "$sum" != "0" ]; then
    exit 1
else
    exit 0
fi